version: '3'

services:
  backend:
    container_name: backend
    image: maven:3.6.3-jdk-8
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
    command: [
      "mvn",
      "spring-boot:run",
      "-Dspring-boot.run.profiles=local"
    ]
    depends_on:
      - database
      - redis

  database:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
      MYSQL_USER: nicol
      MYSQL_PASSWORD: Password1
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
volumes:
  db_data: {}
