spring:
  profiles: local

  datasource:
    url: jdbc:mysql://mysql:3306/test-db
    username: nicol
    password: Password1

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      repositories:
        enabled: false

  session:
    store-type: redis

  liquibase:
    enabled: true
    change-log: classpath:/database/changelogs/master-changelog.yml

  cache:
    type: redis
